// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price.proto

package service2;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string foodType = 1;</code>
   */
  java.lang.String getFoodType();
  /**
   * <code>string foodType = 1;</code>
   */
  com.google.protobuf.ByteString
      getFoodTypeBytes();

  /**
   * <code>double quantity = 2;</code>
   */
  double getQuantity();
}
