// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: batch.proto

package service3;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string foodItem = 1;</code>
   */
  java.lang.String getFoodItem();
  /**
   * <code>string foodItem = 1;</code>
   */
  com.google.protobuf.ByteString
      getFoodItemBytes();
}
